services:

    #
    # Event Listeners
    #
    mmoreram.controllerextra.event_listeners.resolver_event_listener:
        class: %mmoreram.controllerextra.event_listeners.resolver_event_listener.class%
        arguments:
            kernel: @kernel
            annotations_reader: @annotation_reader
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }