parameters:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.json_resolver_annotation_resolver.class: Mmoreram\ControllerExtraBundle\Resolver\JsonResponseAnnotationResolver

services:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.json_resolver_annotation_resolver:
        class: %mmoreram.controllerextra.resolver.json_resolver_annotation_resolver.class%
        arguments:
            default_status: %mmoreram.controllerextra.json_response_default_status%
            default_headers: %mmoreram.controllerextra.json_response_default_headers%
        tags:
            - { name: controller_extra.annotation }
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: -128 }
