language: php

sudo: false

env:
    COMPOSER_OPTIONS=""

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
    include:
        - php: 5.4
          env: COMPOSER_OPTIONS="--prefer-lowest"

env:
    - SYMFONY_VERSION="~2.3"

before_install:
    - composer require --no-update symfony/monolog-bundle:~2.3
    - composer require --no-update symfony/form:~2.3
    - composer require --no-update doctrine/orm:~2.3
    - composer require --no-update white-october/pagerfanta-bundle:~1.0

install:
    - composer update --prefer-source --no-interaction ${COMPOSER_OPTIONS}

script:
    - phpunit

notifications:
    email: false
