language: php

sudo: false

matrix:
    include:
        - php: 7.1
          env: $SYMFONY_VERSION="^3.2"

before_install:
    - 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;'

install:
    - composer update --prefer-source --no-interaction ${COMPOSER_OPTIONS}

script:
    - php vendor/bin/phpunit

notifications:
    email: false
